USERNAME_FIELD = ('xpath', '//*[@id="user-name"]')
PASSWORD_FIELD = ('xpath', '//*[@id="password"]')
LOGIN_BUTTON = ('xpath', '//*[@id="login-button"]')
CARDS = ("css selector", "div[data-test='inventory-item']")
TITLE = ('xpath', '//*[@id="header_container"]/div[2]/span')
ADDITEM_BUTTON = ('xpath', '//*[@id="add-to-cart-sauce-labs-backpack"]')
ITEMINCART_FIELD = ('xpath', '//*[@id="shopping_cart_container"]/a/span')
